### ISSUE TITLE
Don't trust this.. This is a Trojan.

### ISSUE THREAD

**Issue by Aeroverra** [FloppyDolphin57/HorionDebugInjector#14]
This seems to have been recompiled with a trojan

Here is the source of the client. A simple loader or injector will not cause this to be flagged.
https://github.com/horionclient/Horion

I have an opensource one that works on my GitHub that will not set off your virus protection. Enjoy :)

**Comment by ghost** [comment]
this is a loader for the client,
its not obfuscated and can be reversed using
a tool like dnspy. stop making moronic issues because
you clearly have no idea what you are talking about

edit: 
![image](https://user-images.githubusercontent.com/76058207/109433049-a3225880-7a0e-11eb-8985-1b939c088006.png)
😆

**Comment by Aeroverra** [comment]
> this is a loader for the client,
> its not obfuscated and can be reversed using
> a tool like dnspy. stop making moronic issues because
> you clearly have no idea what you are talking about
> 
> edit:
> ![image](https://user-images.githubusercontent.com/76058207/109433049-a3225880-7a0e-11eb-8985-1b939c088006.png)
> 😆

You can attempt to use gaslighting all you want but my statement still stands. I'm doing my best to look out for the end user.
Also you don't need a DNS spy to determine this is malware. The fact that the repo owner doesn't provide the source despite this being someone else's open source project makes it pretty obvious. The response to "decompile it yourself" to most of whom are end users is pretty telling. If that still isn't enough, you can compile the open source project via the link I provided and that doesn't set off antivirus.

**Comment by ghost** [comment]
> Also you don't need a DNS spy to determine this is malware. The fact that the repo owner doesn't provide the source despite this being someone else's open source project makes it pretty obvious. The response to "decompile it yourself" to most of whom are end users is pretty telling. If that still isn't enough, you can compile the open source project via the link I provided and that doesn't set off antivirus.

You are basing everything off of assumption. If you’re an expert, look for yourself, there is no malware.

> The response to "decompile it yourself" to most of whom are end users is pretty telling. 

Ive told the repository owner to do this multiple times before and he is just lazy

> this is malware

I know him and I doubt he would do this, and I know he hasn’t because I bothered to check before making ridiculous claims. 

Your entire argument is based off of the assumption that “not open source and has false positives??? Malware alert”

> You can attempt to use gaslighting all you want but my statement still stands. I'm doing my best to look out for the end user.

Me saying you made a moronic issue and that you have no idea what your talking about can be seen, as mentioned in the sentence below, in the fact you dont even know what this is. You thought it was the client. It was not gaslighting, it was telling the truth.

If you contact him on discord, he will probably provide you with the source as he has done for others who’ve claimed its malware. And just to prove you didnt bother confirming its malware at all, you literally claimed it WAS the client, you didnt even know it was a loader for it. You cant accuse without even knowing what it is.

And another thing, this has 20,000 downloads on github alone, that doesnt count redistribution and people sending the executable to each other. If it were truly malware, Im sure someone with substantial evidence would have come and said something by now.

**Comment by ghost** [comment]
[src.zip](https://github.com/FloppyDolphin57/HorionDebugInjector/files/6060202/src.zip)

**Comment by ghost** [comment]
> If that still isn't enough, you can compile the open source project via the link I provided and that doesn't set off antivirus.

Just noticed this line, it's almost if you didn't read my original statement. THIS ISNT HORION. This is an injector FOR horion
